const fakeHouseRentData = [
  {
    name : "Washington Avenue",
    location : "Nasirabad H/S Chattagram",
    bedroom : 3,
    bathroom : 2,
    img : "https://lh3.googleusercontent.com/N-b1i_Bi6YpZV6iWAv3xOHVo77yWvz7aJym2Sd_H1Xb28jI2wR6Fsn1Qgp7ULWQXyAjzCwUc38tVb-pNFuHiG8qBL29URN6lU0T1LnIVXsAeeOzdPk6tGO0loHKDvx_oCLlwo0VLQQ=w2400",
    img1 : "https://lh3.googleusercontent.com/6RmCWJBOkIg5FlFMsZFYgEZG_RNjbSs-6uVrt3OjR0NXDEmyyEDEtoodg6luWgZoKgV-lSS4UIGkxUCT96cggffI5QkRQ-a9UUygqZOpb_5vciz_Ttgw8gZlNwD-5fOXxPYEXvJDxQ=w2400",
    img2 : "https://lh3.googleusercontent.com/fb1CHdNK3_GJdtQ5NP_tvngXLnQSPqwnvkO4PCMMEZA-9oajBvp5-dj5se5iQz6cOC93MnFSJTq9NFVGMqPfZH_KbwsYXHD0IwS7d2OEXtyL9HAC59xSlkX-nLcSeaogKhToTVhfww=w2400",
    img3 : "https://lh3.googleusercontent.com/KAl6s5r6B2JO4OhS9-dD6KxMMIKqykg6kkfaVrBOYDLuKJADF1AOBvDWgrkyxmg8Z7BKju-EvbCI7RCsJSh4paUCrBLXl0481lGG6G3tLAr-zO0NSqdSRbTR3L97xpxByE3BwOZ21w=w2400",
    img4 : "https://lh3.googleusercontent.com/UHe-7DImdABPd1pU1W7CVnYPw-h66Sv-GtO-wRiU7SaQK_8IkglFukiCeWcwkxvPeylYPbEvBHx_QNOdfj8pKYw1mzw56HMDaXXot9gcrWOXnIUpsaxAspFNUiV2TwS5B6hM7JWIiQ=w2400",
    shortDescription : "3000 sq-ft, 3 BedRoom, Semi-furnished, Luxurious, South Facing Apartment for Rent in Rangs Malancha, Melbourne",
    price : 194,
    rent : 576,
    serviceCharge : 8000,
    securityDeposit : 3,
    flateReleasePolicy : 3,
    address : "Rangs Malancha, House-68,Road-6A(Dead End Road),Dhanmondi Residential Area",
    flatSize : 3000,
    floor : "A5(5th Floor)(6 storied Building)(South Facing Unit)",
    roomCategory : "3 large Bed Rooms With 3 Varendas, Spacious Deawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room And Servant room with Attached Toilet",
    facilities : "1 Modern Lift, All Modern Amenities & Semi Furnished.",
    additionalFacilities : "a. Electricity with full generatoe load, b. Central Gas Geyser, c. 2 Car parking with 1 Driver's Accomodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging Facilty with CC camera"
  },
  {
    name : "Family Apartment Three",
    location : "Nasirabad H/S Chattagram",
    bedroom : 3,
    bathroom : 2,
    img : "https://lh3.googleusercontent.com/C_gmN7Kg0IrrpYSKpTtTPlZZXMYOspwZ-ozxrGZ2Q6dSTHq6VPi7aBalEuCMx6VLYmH25ywOHGOWzu5TMxA8ek0bksCLNaobkQ3FXrWrDMM4WMvrNQuYFihmSqrAzSA1KsjCJzJY7A=w2400",
    img1 : "https://lh3.googleusercontent.com/6RmCWJBOkIg5FlFMsZFYgEZG_RNjbSs-6uVrt3OjR0NXDEmyyEDEtoodg6luWgZoKgV-lSS4UIGkxUCT96cggffI5QkRQ-a9UUygqZOpb_5vciz_Ttgw8gZlNwD-5fOXxPYEXvJDxQ=w2400",
    img2 : "https://lh3.googleusercontent.com/fb1CHdNK3_GJdtQ5NP_tvngXLnQSPqwnvkO4PCMMEZA-9oajBvp5-dj5se5iQz6cOC93MnFSJTq9NFVGMqPfZH_KbwsYXHD0IwS7d2OEXtyL9HAC59xSlkX-nLcSeaogKhToTVhfww=w2400",
    img3 : "https://lh3.googleusercontent.com/KAl6s5r6B2JO4OhS9-dD6KxMMIKqykg6kkfaVrBOYDLuKJADF1AOBvDWgrkyxmg8Z7BKju-EvbCI7RCsJSh4paUCrBLXl0481lGG6G3tLAr-zO0NSqdSRbTR3L97xpxByE3BwOZ21w=w2400",
    img4 : "https://lh3.googleusercontent.com/UHe-7DImdABPd1pU1W7CVnYPw-h66Sv-GtO-wRiU7SaQK_8IkglFukiCeWcwkxvPeylYPbEvBHx_QNOdfj8pKYw1mzw56HMDaXXot9gcrWOXnIUpsaxAspFNUiV2TwS5B6hM7JWIiQ=w2400",
    shortDescription : "3000 sq-ft, 3 BedRoom, Semi-furnished, Luxurious, South Facing Apartment for Rent in Rangs Malancha, Melbourne",
    price : 356,
    rent : 576,
    serviceCharge : 8000,
    securityDeposit : 3,
    flateReleasePolicy : 3,
    address : "Rangs Malancha, House-68,Road-6A(Dead End Road),Dhanmondi Residential Area",
    flatSize : 3000,
    floor : "A5(5th Floor)(6 storied Building)(South Facing Unit)",
    roomCategory : "3 large Bed Rooms With 3 Varendas, Spacious Deawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room And Servant room with Attached Toilet",
    facilities : "1 Modern Lift, All Modern Amenities & Semi Furnished.",
    additionalFacilities : "a. Electricity with full generatoe load, b. Central Gas Geyser, c. 2 Car parking with 1 Driver's Accomodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging Facilty with CC camera"
  },
  {
    name : "Gorgeous House",
    location : "Nasirabad H/S Chattagram",
    bedroom : 3,
    bathroom : 2,
    img : "https://lh3.googleusercontent.com/zIVPFwq8rEtuuWtRid2JQl6AiVvVN7G9Yj6qgMxIY6J2erWBZ0XjpYFYvgn6cXUZLin__YHKTJGdfo0f6QEH0ZW4DJtrzpIYfKsIzZYM505Ym3MYMREQZ5L6o20rArZ4H3Yn2JYqZQ=w2400",
    img1 : "https://lh3.googleusercontent.com/6RmCWJBOkIg5FlFMsZFYgEZG_RNjbSs-6uVrt3OjR0NXDEmyyEDEtoodg6luWgZoKgV-lSS4UIGkxUCT96cggffI5QkRQ-a9UUygqZOpb_5vciz_Ttgw8gZlNwD-5fOXxPYEXvJDxQ=w2400",
    img2 : "https://lh3.googleusercontent.com/fb1CHdNK3_GJdtQ5NP_tvngXLnQSPqwnvkO4PCMMEZA-9oajBvp5-dj5se5iQz6cOC93MnFSJTq9NFVGMqPfZH_KbwsYXHD0IwS7d2OEXtyL9HAC59xSlkX-nLcSeaogKhToTVhfww=w2400",
    img3 : "https://lh3.googleusercontent.com/KAl6s5r6B2JO4OhS9-dD6KxMMIKqykg6kkfaVrBOYDLuKJADF1AOBvDWgrkyxmg8Z7BKju-EvbCI7RCsJSh4paUCrBLXl0481lGG6G3tLAr-zO0NSqdSRbTR3L97xpxByE3BwOZ21w=w2400",
    img4 : "https://lh3.googleusercontent.com/UHe-7DImdABPd1pU1W7CVnYPw-h66Sv-GtO-wRiU7SaQK_8IkglFukiCeWcwkxvPeylYPbEvBHx_QNOdfj8pKYw1mzw56HMDaXXot9gcrWOXnIUpsaxAspFNUiV2TwS5B6hM7JWIiQ=w2400",
    shortDescription : "3000 sq-ft, 3 BedRoom, Semi-furnished, Luxurious, South Facing Apartment for Rent in Rangs Malancha, Melbourne",
    price : 256,
    rent : 576,
    serviceCharge : 8000,
    securityDeposit : 3,
    flateReleasePolicy : 3,
    address : "Rangs Malancha, House-68,Road-6A(Dead End Road),Dhanmondi Residential Area",
    flatSize : 3000,
    floor : "A5(5th Floor)(6 storied Building)(South Facing Unit)",
    roomCategory : "3 large Bed Rooms With 3 Varendas, Spacious Deawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room And Servant room with Attached Toilet",
    facilities : "1 Modern Lift, All Modern Amenities & Semi Furnished.",
    additionalFacilities : "a. Electricity with full generatoe load, b. Central Gas Geyser, c. 2 Car parking with 1 Driver's Accomodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging Facilty with CC camera"
  },
  {
    name : "Luxury Villa",
    location : "Nasirabad H/S Chattagram",
    bedroom : 3,
    bathroom : 2,
    img : "https://lh3.googleusercontent.com/5GGrwKbLDsWqDOvHESpVPlTlP28Xf6UKxwtGlPhwbAij4cyzNu9Ke1kHwQH_zi6Y8kJww8XglqcYSyqUpfsN-Kn4EyW0YVZPgGiMj3N7LQ6ZPmtSQcnr-4PJh-I4Mh3vHU-p4TCKnw=w2400",
    img1 : "https://lh3.googleusercontent.com/6RmCWJBOkIg5FlFMsZFYgEZG_RNjbSs-6uVrt3OjR0NXDEmyyEDEtoodg6luWgZoKgV-lSS4UIGkxUCT96cggffI5QkRQ-a9UUygqZOpb_5vciz_Ttgw8gZlNwD-5fOXxPYEXvJDxQ=w2400",
    img2 : "https://lh3.googleusercontent.com/fb1CHdNK3_GJdtQ5NP_tvngXLnQSPqwnvkO4PCMMEZA-9oajBvp5-dj5se5iQz6cOC93MnFSJTq9NFVGMqPfZH_KbwsYXHD0IwS7d2OEXtyL9HAC59xSlkX-nLcSeaogKhToTVhfww=w2400",
    img3 : "https://lh3.googleusercontent.com/KAl6s5r6B2JO4OhS9-dD6KxMMIKqykg6kkfaVrBOYDLuKJADF1AOBvDWgrkyxmg8Z7BKju-EvbCI7RCsJSh4paUCrBLXl0481lGG6G3tLAr-zO0NSqdSRbTR3L97xpxByE3BwOZ21w=w2400",
    img4 : "https://lh3.googleusercontent.com/UHe-7DImdABPd1pU1W7CVnYPw-h66Sv-GtO-wRiU7SaQK_8IkglFukiCeWcwkxvPeylYPbEvBHx_QNOdfj8pKYw1mzw56HMDaXXot9gcrWOXnIUpsaxAspFNUiV2TwS5B6hM7JWIiQ=w2400",
    shortDescription : "3000 sq-ft, 3 BedRoom, Semi-furnished, Luxurious, South Facing Apartment for Rent in Rangs Malancha, Melbourne",
    price : 345,
    rent : 576,
    serviceCharge : 8000,
    securityDeposit : 3,
    flateReleasePolicy : 3,
    address : "Rangs Malancha, House-68,Road-6A(Dead End Road),Dhanmondi Residential Area",
    flatSize : 3000,
    floor : "A5(5th Floor)(6 storied Building)(South Facing Unit)",
    roomCategory : "3 large Bed Rooms With 3 Varendas, Spacious Deawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room And Servant room with Attached Toilet",
    facilities : "1 Modern Lift, All Modern Amenities & Semi Furnished.",
    additionalFacilities : "a. Electricity with full generatoe load, b. Central Gas Geyser, c. 2 Car parking with 1 Driver's Accomodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging Facilty with CC camera"
  },
  {
    name : "Epic Huda Palacio",
    location : "Nasirabad H/S Chattagram",
    bedroom : 3,
    bathroom : 2,
    img : "https://lh3.googleusercontent.com/8mVDpn5Jhm4Qaq8PbjFsIFDLvx2LRMMG_MBJ8Jh8kRuqUgdwLfkVc_vY-vrDUJQRtBWMhwqCFYAE-Ra_ZI2g5Du5hOuPqm4rczf3GvOa0E4wHxfc-mB51oUmNC31pbzs2FkPqsovKQ=w2400",
    img1 : "https://lh3.googleusercontent.com/6RmCWJBOkIg5FlFMsZFYgEZG_RNjbSs-6uVrt3OjR0NXDEmyyEDEtoodg6luWgZoKgV-lSS4UIGkxUCT96cggffI5QkRQ-a9UUygqZOpb_5vciz_Ttgw8gZlNwD-5fOXxPYEXvJDxQ=w2400",
    img2 : "https://lh3.googleusercontent.com/fb1CHdNK3_GJdtQ5NP_tvngXLnQSPqwnvkO4PCMMEZA-9oajBvp5-dj5se5iQz6cOC93MnFSJTq9NFVGMqPfZH_KbwsYXHD0IwS7d2OEXtyL9HAC59xSlkX-nLcSeaogKhToTVhfww=w2400",
    img3 : "https://lh3.googleusercontent.com/KAl6s5r6B2JO4OhS9-dD6KxMMIKqykg6kkfaVrBOYDLuKJADF1AOBvDWgrkyxmg8Z7BKju-EvbCI7RCsJSh4paUCrBLXl0481lGG6G3tLAr-zO0NSqdSRbTR3L97xpxByE3BwOZ21w=w2400",
    img4 : "https://lh3.googleusercontent.com/UHe-7DImdABPd1pU1W7CVnYPw-h66Sv-GtO-wRiU7SaQK_8IkglFukiCeWcwkxvPeylYPbEvBHx_QNOdfj8pKYw1mzw56HMDaXXot9gcrWOXnIUpsaxAspFNUiV2TwS5B6hM7JWIiQ=w2400",
    shortDescription : "3000 sq-ft, 3 BedRoom, Semi-furnished, Luxurious, South Facing Apartment for Rent in Rangs Malancha, Melbourne",
    price : 536,
    rent : 576,
    serviceCharge : 8000,
    securityDeposit : 3,
    flateReleasePolicy : 3,
    address : "Rangs Malancha, House-68,Road-6A(Dead End Road),Dhanmondi Residential Area",
    flatSize : 3000,
    floor : "A5(5th Floor)(6 storied Building)(South Facing Unit)",
    roomCategory : "3 large Bed Rooms With 3 Varendas, Spacious Deawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room And Servant room with Attached Toilet",
    facilities : "1 Modern Lift, All Modern Amenities & Semi Furnished.",
    additionalFacilities : "a. Electricity with full generatoe load, b. Central Gas Geyser, c. 2 Car parking with 1 Driver's Accomodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging Facilty with CC camera"
  },
  {
    name : "Washington Avenue",
    location : "Nasirabad H/S Chattagram",
    bedroom : 3,
    bathroom : 2,
    img : "https://lh3.googleusercontent.com/qFVJstiKieRsh5YADi7kTk4mY7qCetQUuki8iqtVeLf-mm5LRy2wQ0a4mvSOdZzjTcfgDOPDKNCrcaNHA2_R_CQiYlv2Kq7J9k0WZ--WEAty43RbZ6LJ-UHVH52NFh09ZYdUCaWTKw=w2400",
    img1 : "https://lh3.googleusercontent.com/6RmCWJBOkIg5FlFMsZFYgEZG_RNjbSs-6uVrt3OjR0NXDEmyyEDEtoodg6luWgZoKgV-lSS4UIGkxUCT96cggffI5QkRQ-a9UUygqZOpb_5vciz_Ttgw8gZlNwD-5fOXxPYEXvJDxQ=w2400",
    img2 : "https://lh3.googleusercontent.com/fb1CHdNK3_GJdtQ5NP_tvngXLnQSPqwnvkO4PCMMEZA-9oajBvp5-dj5se5iQz6cOC93MnFSJTq9NFVGMqPfZH_KbwsYXHD0IwS7d2OEXtyL9HAC59xSlkX-nLcSeaogKhToTVhfww=w2400",
    img3 : "https://lh3.googleusercontent.com/KAl6s5r6B2JO4OhS9-dD6KxMMIKqykg6kkfaVrBOYDLuKJADF1AOBvDWgrkyxmg8Z7BKju-EvbCI7RCsJSh4paUCrBLXl0481lGG6G3tLAr-zO0NSqdSRbTR3L97xpxByE3BwOZ21w=w2400",
    img4 : "https://lh3.googleusercontent.com/UHe-7DImdABPd1pU1W7CVnYPw-h66Sv-GtO-wRiU7SaQK_8IkglFukiCeWcwkxvPeylYPbEvBHx_QNOdfj8pKYw1mzw56HMDaXXot9gcrWOXnIUpsaxAspFNUiV2TwS5B6hM7JWIiQ=w2400",
    shortDescription : "3000 sq-ft, 3 BedRoom, Semi-furnished, Luxurious, South Facing Apartment for Rent in Rangs Malancha, Melbourne",
    rent : 576,
    price : 283,
    serviceCharge : 8000,
    securityDeposit : 3,
    flateReleasePolicy : 3,
    address : "Rangs Malancha, House-68,Road-6A(Dead End Road),Dhanmondi Residential Area",
    flatSize : 3000,
    floor : "A5(5th Floor)(6 storied Building)(South Facing Unit)",
    roomCategory : "3 large Bed Rooms With 3 Varendas, Spacious Deawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room And Servant room with Attached Toilet",
    facilities : "1 Modern Lift, All Modern Amenities & Semi Furnished.",
    additionalFacilities : "a. Electricity with full generatoe load, b. Central Gas Geyser, c. 2 Car parking with 1 Driver's Accomodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging Facilty with CC camera"
  }
]

export default fakeHouseRentData;
